### ISSUE TITLE
Create overlay of different shapes

### ISSUE THREAD

**Issue by mkfreeman** [VSRS-UW/bd_vizualization#6]
Multiple overlapping elements (e.g., lichens)

**Comment by kitchensjn** [comment]
A base version of this feature for stationary visualizations has been completed within the LayeredVoronoiAndPerlin directory. Currently lacking jitter due to poor compatibility between the Voronoi library and p5.js Instance Mode. This has not yet been implemented within the animation style visualization, though may be looked into down the road.
